#####################################################################
# Configuration Spring de base
#####################################################################
# app name
spring:
  application:
    name:                            rentes-service
  #jackson null default desactivate
  jackson:
    default-property-inclusion:      NON_NULL
#profiles spring
  profiles:
    active:                          db2,maison

# mode jar, port et context
server:
  port:                              ${PORT:9020}
  servlet.context-path:                        /rentes-service
#####################################################################
# Configuration Spring actuator
#####################################################################
management:
  server.servlet.context-path:                         /actuator

# configuration des endpoints
management:
  endpoint:
    hypermedia:
      enabled:                            true
    actuator:
      enabled:                            true
    beans:
      enabled:                            true
    env:
      enabled:                            true
    metrics:
      enabled:                            true
    health:
      enabled:                            true
    mappings:
      enabled:                            true
    docs:
      enabled:                            true
    logfile:
      enabled:                            true

